# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  name: SBAgentPool

variables:
  buildConfiguration: 'Release'
  sqlScriptPath: 'D:\AzureTest\DemoSQL.sql'
  logFilePath: 'D:\AzureTest\OutPut.txt'
  serverName: '(LocalDb)\MSSQLLocalDB'
  databaseName: 'TrafficDB'
  username: 'TestLogin'
  pwd: 'Test1'


steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet >=1.0.0'
  inputs:
    versionSpec: '>=1.0.0'

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(Parameters.solution)'

- task: DotNetCoreCLI@2
  displayName: 'Build project'
  inputs:
    command: 'build'
    projects: '**/*.sln'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish Project'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.sln'
    arguments: '--configuration $(buildConfiguration)  --output $(build.artifactstagingdirectory)\Build$(Build.BuildId)'
    zipAfterPublish: false

- task: CmdLine@2
  displayName: 'Backup Old Folder'
  inputs:
    script: |
      xcopy "$(build.artifactstagingdirectory)" "D:\AzureTest\Backup_Artifacts" /s /y

- task: CmdLine@2
  displayName: 'Add Artifact Folder to Publish folder'
  inputs:
    script: |
      xcopy "$(build.artifactstagingdirectory)\Build$(Build.BuildId)" "D:\AzureTest\AzurePublish" /s /y

- task: PowerShell@2
  inputs:
    filePath: 'Invoke-Sqlcmd -ServerInstance $(serverName) -Database $(databaseName) -Username "$(username)" -Password "$(pwd)" -InputFile $(sqlScriptPath) | Out-File -FilePath $(logFilePath) -Verbose'
- task: CmdLine@2
  inputs:
    script: |
      cd /d D:\AzureTest
      test
      
- task: CmdLine@2
  inputs:
    script: |
      cd /d D:\AzureTest
      WinAuthSqlBat

- task: CmdLine@2
  inputs:
    script: |
      cd /d D:\AzureTest
      SqlTest

