# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  name: SBAgentPool

steps:

- task: PowerShell@2
  displayName: 'Run batch file as administrator'
  inputs:
   targetType: 'filePath'
   filePath: 'D:\AzureTest\test.bat'
   arguments: ''
   errorActionPreference: 'stop'
  condition: eq(variables['Agent.OS'], 'Windows_NT')

