# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  name: SBAgentPool

steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet >=1.0.0'
  inputs:
    versionSpec: '>=1.0.0'

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(Parameters.solution)'

- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '**/*.sln'
    msbuildArgs: '/p:DeployOnBuild=true /p:SkipInvalidConfigurations=true /p:PublishUrl="$(build.artifactstagingdirectory)/$(Build.BuildId)" '
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- task: CmdLine@2
  displayName: 'Add Artifact Folder to Publish folder'
  inputs:
    script: |
      xcopy "$(build.artifactstagingdirectory)/$(Build.BuildId)" "D:\AzureTest\AzurePublish" /s /y

- task: CmdLine@2
  inputs:
    script: |
      cd /d $(Agent.HomeDirectory)
      cd /d D:\AzureTest\test.bat