# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  name: SBAgentPool

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: CmdLine@2
  inputs:
    script: |
      cd /d D:\AzureTest
      SqlTest

- task: PowerShell@2
  inputs:
    filePath: 'D:\AzureTest\testPS.ps1'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Invoke-Sqlcmd -ServerInstance $(serverName) -Database $(databaseName) -Username "$(username)" -Password "$(pwd)" -InputFile $(sqlScriptPath) | Out-File -FilePath $(logFilePath) -Verbose'

- task: CmdLine@2
  inputs:
    script: |
      cd /d D:\AzureTest
      test

- task: CmdLine@2
  inputs:
    script: |
      cd /d D:\AzureTest
      WinAuthSqlBat
